title: yzh119
tagline: notes & writing
description: A minimalist blog.
author: Zihao Ye
email: your-email@example.com
url: "https://yzh119.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 10

# GitHub Pages compatible plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social (optional, edit or remove)
github_username: yzh119

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
